meta_product_name: "Baby Steps"
meta_title: "Baby Steps -  Chronicle your newborn's adventures, offer the gift of a lifetime"
meta_description: "Chronicle your newborn's adventures, offer the gift of a lifetime"
meta_image: "meta_cover.jpg" # should exist in `app/assets/images/`
twitter_account: "@baby__steps" # required for Twitter Cards
